#!/usr/bin/env python3
"""Verify the exported currency pack independently of the backend checkout.

The pack is generated by the backend, so this also verifies the record the
backend wrote beside it and that the contract revision the transport sends is
the same one the pack was generated from.
"""
import hashlib
import json
import re
from pathlib import Path

PROJECT = Path(__file__).resolve().parents[1]
ROOT = PROJECT / 'assets/reference/currencies'
manifest = json.loads((ROOT / 'manifest.json').read_text())
assert manifest['schema_version'] == 1
assert manifest['cldr_version'] == '48.0.0'
hashes = manifest['files']
encoded = (json.dumps(hashes, ensure_ascii=False, indent=2, sort_keys=True) + '\n').encode()
assert hashlib.sha256(encoded).hexdigest() == manifest['content_sha256']
for path, expected in hashes.items():
    target = (ROOT / path).resolve()
    assert target.is_relative_to(ROOT.resolve())
    assert hashlib.sha256(target.read_bytes()).hexdigest() == expected, path
actual = {str(p.relative_to(ROOT)) for p in ROOT.rglob('*') if p.is_file()}
assert actual == set(hashes) | {'manifest.json'}
catalog = json.loads((ROOT / manifest['catalog']).read_text())['currencies']
assert len(catalog) == 148
for locale, info in manifest['locales'].items():
    data = json.loads((ROOT / info['path']).read_text())
    assert data['locale'] == locale
    assert set(data['currencies']) == set(catalog)
    assert all(v['display_name'] and v['symbol'] for v in data['currencies'].values())
assert not (ROOT.parent / 'currencies.json').exists(), 'Remove the retired bilingual catalog'

# The backend writes this record when it exports the pack. A missing or stale
# record means the backend changed without re-exporting, which no other check
# in either repository would notice.
contract = json.loads((PROJECT / 'assets/reference/contract.json').read_text())
assert contract['schema_version'] == 1
assert contract['currency_pack_sha256'] == manifest['content_sha256'], (
    'The contract record does not describe this pack; re-export with '
    '`just export-currencies <app>`'
)
assert contract['cldr_version'] == manifest['cldr_version']

transport = (PROJECT / 'lib/core/network/ledger_transport.dart').read_text()
match = re.search(r"static const version = '([0-9]{4}-[0-9]{2}-[0-9]{2})';", transport)
assert match, 'The transport API version constant moved or changed shape'
assert match.group(1) == contract['contract_revision'], (
    f"The transport sends {match.group(1)} but the exported pack came from "
    f"{contract['contract_revision']}"
)

print(
    f'Currency pack verified: {len(catalog)} currencies, '
    f'{len(manifest["locales"])} locale bundles, '
    f'contract {contract["contract_revision"]}'
)
